### PR TITLE
Insert minimal podspec file to allow inclusion via Cocoapods.

### PR DESCRIPTION
**Pull request by vokal-isaac**
I haven't looked into exactly what this library does, but I'd like to include it via Cocoapods instead of as a git submodule, so here we are.

@vokal/ios-developers Review please?

### CODE REVIEW

**Comment by designatednerd** [comment]
That is in fact a podspec. I would recommend waiting to push it to `trunk` until we've got a better handle on what this is/does. 

LGTM. Anyone else?

**Comment by vokal-isaac** [comment]
I wasn't planning to push it to trunk at all, especially since there's no license specified; just going to reference the repo directly.

**Comment by naomihimley** [comment]
@vokal-isaac I think its actually Trunq

**Comment by designatednerd** [comment]
@vokal-isaac :+1: 

@naomihimley  I :eyes: what you did there

**Comment by vokal-isaac** [comment]
Mergeable?

**Pull request merged**
